### ISSUE TITLE
Can't Download Module

### ISSUE THREAD

**Issue by webmaster94** [Tabletop-RPG-Music/tabletop-rpg-music#12]
I have had some recent issues where the module can no longer update and after attempting to re-install the module, it gets stuck at 99% for a awhile and eventually produces the following error: 
FoundryVTT | 2023-06-17 02:15:59 | [error] Cannot read property 'entryCount' of undefined
TypeError: Cannot read property 'entryCount' of undefined
    at file:///C:/Program%20Files/FoundryVTT/resources/app/dist/files/files.mjs:1:1610
    at C:\Program Files\FoundryVTT\resources\app\node_modules\yauzl\index.js:34:21
    at FSReqCallback.oncomplete (node:fs:185:23)
FoundryVTT | 2023-06-17 02:15:59 | [info] ENOENT: no such file or directory, open 'C:\Users\<redacted>\AppData\Local\FoundryVTT\Data\modules\tabletop-rpg-music.zip' - 100%
FoundryVTT | 2023-06-17 02:15:59 | [info] Cleaning Up Artifacts - 100%
FoundryVTT | 2023-06-17 02:15:59 | [error] ENOENT: no such file or directory, unlink 'C:\Users\<redacted>\AppData\Local\FoundryVTT\Data\modules\tabletop-rpg-music.zip'
Error: ENOENT: no such file or directory, unlink 'C:\Users\<redacted>\AppData\Local\FoundryVTT\Data\modules\tabletop-rpg-music.zip'
    at Object.unlinkSync (node:fs:1708:3)
    at file:///C:/Program%20Files/FoundryVTT/resources/app/dist/packages/installer.mjs:1:1560
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Running Foundry v10 Build 291. 

Any assistance is much appreciated.

**Comment by Tabletop-RPG-Music** [comment]
Thanks for sending this along, I’ll look into it

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: webmaster94 ***@***.***>
Sent: Saturday, June 17, 2023 8:21:27 AM
To: Tabletop-RPG-Music/tabletop-rpg-music ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Tabletop-RPG-Music/tabletop-rpg-music] Can't Download Module (Issue #12)


I have had some recent issues where the module can no longer update and after attempting to re-install the module, it gets stuck at 99% for a awhile and eventually produces the following error:
FoundryVTT | 2023-06-17 02:15:59 | [error] Cannot read property 'entryCount' of undefined
TypeError: Cannot read property 'entryCount' of undefined
at file:///C:/Program%20Files/FoundryVTT/resources/app/dist/files/files.mjs:1:1610
at C:\Program Files\FoundryVTT\resources\app\node_modules\yauzl\index.js:34:21
at FSReqCallback.oncomplete (node:fs:185:23)
FoundryVTT | 2023-06-17 02:15:59 | [info] ENOENT: no such file or directory, open 'C:\Users<redacted>\AppData\Local\FoundryVTT\Data\modules\tabletop-rpg-music.zip' - 100%
FoundryVTT | 2023-06-17 02:15:59 | [info] Cleaning Up Artifacts - 100%
FoundryVTT | 2023-06-17 02:15:59 | [error] ENOENT: no such file or directory, unlink 'C:\Users<redacted>\AppData\Local\FoundryVTT\Data\modules\tabletop-rpg-music.zip'
Error: ENOENT: no such file or directory, unlink 'C:\Users<redacted>\AppData\Local\FoundryVTT\Data\modules\tabletop-rpg-music.zip'
at Object.unlinkSync (node:fs:1708:3)
at file:///C:/Program%20Files/FoundryVTT/resources/app/dist/packages/installer.mjs:1:1560
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)

Running Foundry v10 Build 291.

Any assistance is much appreciated.
